[build]
  command = "pnpm build"
  publish = ".next"

[dev]
  command = "next dev"

[[headers]]
  for = "/_next/static/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"

  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "https://tomokichidiary.netlify.app/*"
  to = "https://travel.tomokichidiary.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/diary/*"
  to = "/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/tourism/*"
  to = "/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/itinerary/*"
  to = "/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/calculator/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/clock"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/personal"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/roulette"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/search"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/diary"
  to = "/posts"
  status = 301
  force = true

[[redirects]]
  from = "/tourism"
  to = "/posts"
  status = 301
  force = true

[[redirects]]
  from = "/itinerary"
  to = "/posts"
  status = 301
  force = true
